amp: true
batch: 24
box: 7.5
cache: false
cls: 0.5
copy_paste: 0.0
degrees: 15.0
device: 0
dfl: 1.5
epochs: 150
fliplr: 0.5
flipud: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
lr0: 0.001
lrf: 0.01
mixup: 0.1
model: C:\Users\student\Desktop\Solar Project\training\yolov11m.pt
momentum: 0.937
mosaic: 1.0
optimizer: AdamW
patience: 25
perspective: 0.0
save_period: 10
scale: 0.5
shear: 0.0
translate: 0.1
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 0
