amp: true
batch: 1
box: 7.5
cache: false
cls: 0.7
copy_paste: 0.0
degrees: 5.0
device: 0
dfl: 1.5
epochs: 60
fliplr: 0.5
flipud: 0.2
hsv_h: 0.01
hsv_s: 0.5
hsv_v: 0.35
imgsz: 1536
lr0: 0.0003
lrf: 0.1
mixup: 0.05
model: trained_model\yolov11_solar.pt
momentum: 0.937
mosaic: 0.2
optimizer: AdamW
patience: 20
perspective: 0.0
save_period: 5
scale: 0.3
shear: 0.0
translate: 0.08
warmup_bias_lr: 0.1
warmup_epochs: 1.0
warmup_momentum: 0.8
weight_decay: 0.0003
workers: 0
